修正の必要がないcopやファイルを除外
wyrd-team/dbc-s8-ruby pull request #26
Opened 2021-08-23 05:03 UTC by Koute2

タイトル通り

2021-08-25 03:31 UTC, mygkw approved these changes

2021-08-25 03:37 UTC, mygkw requested changes
テスト落ちてたので、一旦approve取り消します

2021-08-25 03:38 UTC, Koute2 commented
あ、すいません
これまだWIPです

2021-08-30 01:44 UTC, mygkw approved these changes

2021-08-30 01:53 UTC, merged